export default [
    { label: 'Genèse', value: 'Gen', ord: '1', chapters: '50' },
    { label: 'Exode', value: 'Exod', ord: '2', chapters: '40' },
    { label: 'Lévitique', value: 'Lev', ord: '3', chapters: '27' },
    { label: 'Nombres', value: 'Num', ord: '4', chapters: '36' },
    { label: 'Deutéronome', value: 'Deut', ord: '5', chapters: '34' },
    { label: 'Josué', value: 'Josh', ord: '6', chapters: '24' },
    { label: 'Juges', value: 'Judg', ord: '7', chapters: '21' },
    { label: 'Ruth', value: 'Ruth', ord: '8', chapters: '4' },
    { label: '1 Samuel', value: '1Sam', ord: '9', chapters: '31' },
    { label: '2 Samuel', value: '2Sam', ord: '10', chapters: '24' },
    { label: '1 Rois', value: '1Kgs', ord: '11', chapters: '22' },
    { label: '2 Rois', value: '2Kgs', ord: '12', chapters: '25' },
    {
        label: '1 Chroniques',
        value: '1Chr',
        ord: '13',
        chapters: '29'
    },
    {
        label: '2 Chroniques',
        value: '2Chr',
        ord: '14',
        chapters: '36'
    },
    { label: 'Esdras', value: 'Ezra', ord: '15', chapters: '10' },
    { label: 'Néhémie', value: 'Neh', ord: '16', chapters: '13' },
    { label: 'Esther', value: 'Esth', ord: '17', chapters: '10' },
    { label: 'Job', value: 'Job', ord: '18', chapters: '42' },
    { label: 'Psaumes', value: 'Ps', ord: '19', chapters: '150' },
    { label: 'Proverbes', value: 'Prov', ord: '20', chapters: '31' },
    { label: 'Ecclésiaste', value: 'Eccl', ord: '21', chapters: '12' },
    { label: 'Cantique', value: 'Song', ord: '22', chapters: '8' },
    { label: 'Ésaïe', value: 'Isa', ord: '23', chapters: '66' },
    { label: 'Jérémie', value: 'Jer', ord: '24', chapters: '52' },
    { label: 'Lamentations', value: 'Lam', ord: '25', chapters: '5' },
    { label: 'Ézékiel', value: 'Ezek', ord: '26', chapters: '48' },
    { label: 'Daniel', value: 'Dan', ord: '27', chapters: '12' },
    { label: 'Osée', value: 'Hos', ord: '28', chapters: '14' },
    { label: 'Joël', value: 'Joel', ord: '29', chapters: '3' },
    { label: 'Amos', value: 'Amos', ord: '30', chapters: '9' },
    { label: 'Abdias', value: 'Obad', ord: '31', chapters: '1' },
    { label: 'Jonas', value: 'Jonah', ord: '32', chapters: '4' },
    { label: 'Michée', value: 'Mic', ord: '33', chapters: '7' },
    { label: 'Nahum', value: 'Nah', ord: '34', chapters: '3' },
    { label: 'Habacuc', value: 'Hab', ord: '35', chapters: '3' },
    { label: 'Sophonie', value: 'Zeph', ord: '36', chapters: '3' },
    { label: 'Aggée', value: 'Hag', ord: '37', chapters: '2' },
    { label: 'Zacharie', value: 'Zech', ord: '38', chapters: '14' },
    { label: 'Malachie', value: 'Mal', ord: '39', chapters: '4' },
    { label: 'Matthieu', value: 'Matt', ord: '40', chapters: '28' },
    { label: 'Marc', value: 'Mark', ord: '41', chapters: '16' },
    { label: 'Luc', value: 'Luke', ord: '42', chapters: '24' },
    { label: 'Jean', value: 'John', ord: '43', chapters: '21' },
    { label: 'Actes', value: 'Acts', ord: '44', chapters: '28' },
    { label: 'Romains', value: 'Rom', ord: '45', chapters: '16' },
    {
        label: '1 Corinthiens',
        value: '1Cor',
        ord: '46',
        chapters: '16'
    },
    {
        label: '2 Corinthiens',
        value: '2Cor',
        ord: '47',
        chapters: '13'
    },
    { label: 'Galates', value: 'Gal', ord: '48', chapters: '6' },
    { label: 'Éphésiens', value: 'Eph', ord: '49', chapters: '6' },
    { label: 'Philippiens', value: 'Phil', ord: '50', chapters: '4' },
    { label: 'Colossiens', value: 'Col', ord: '51', chapters: '4' },
    {
        label: '1 Thessaloniciens',
        value: '1Thess',
        ord: '52',
        chapters: '5'
    },
    {
        label: '2 Thessaloniciens',
        value: '2Thess',
        ord: '53',
        chapters: '3'
    },
    { label: '1 Timothée', value: '1Tim', ord: '54', chapters: '6' },
    { label: '2 Timothée', value: '2Tim', ord: '55', chapters: '4' },
    { label: 'Tite', value: 'Titus', ord: '56', chapters: '3' },
    { label: 'Philémon', value: 'Phlm', ord: '57', chapters: '1' },
    { label: 'Hébreux', value: 'Heb', ord: '58', chapters: '13' },
    { label: 'Jacques', value: 'Jas', ord: '59', chapters: '5' },
    { label: '1 Pierre', value: '1Pet', ord: '60', chapters: '5' },
    { label: '2 Pierre', value: '2Pet', ord: '61', chapters: '3' },
    { label: '1 Jean', value: '1John', ord: '62', chapters: '5' },
    { label: '2 Jean', value: '2John', ord: '63', chapters: '1' },
    { label: '3 Jean', value: '3John', ord: '64', chapters: '1' },
    { label: 'Jude', value: 'Jude', ord: '65', chapters: '1' },
    { label: 'Apocalypse', value: 'Rev', ord: '66', chapters: '22' }]